export {}; // Make this a module

declare global {
  // This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
  // plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
  // whether you're running in development or production).
  const RENDERER_VITE_DEV_SERVER_URL: string | undefined;
  const RENDERER_VITE_NAME: string;

  const __CATCH_MAIN_EXCEPTIONS__: boolean | undefined;

  interface VitePluginRuntimeKeys {
    VITE_DEV_SERVER_URL: `${string}_VITE_DEV_SERVER_URL`;
    VITE_NAME: `${string}_VITE_NAME`;
  }
}

type VitePluginConfig = ConstructorParameters<
  typeof import("@electron-forge/plugin-vite").VitePlugin
>[0];

declare module "vite" {
  interface ConfigEnv<
    K extends keyof VitePluginConfig = keyof VitePluginConfig,
  > {
    root?: string;
    forgeConfig?: VitePluginConfig;
    forgeConfigSelf?: VitePluginConfig[K][number];
  }
}
